import type {Metadata} from "next";
// import {Geist, Geist_Mono} from "next/font/google";
import {Poppins} from "next/font/google";
import "./globals.css";
import {Navbar} from "./components/layout/Navbar";

import {JoinUsWrapper} from "./components/home/JoinUsWrapper";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});
// const schoolbell = Schoolbell({
//   subsets: ["latin"],
//   weight: "400",
// });

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        // className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        className={`${poppins.className} `}
      >
        <Navbar />
        {children}
        <JoinUsWrapper />
      </body>
    </html>
  );
}
