import type {Metadata} from "next";

import {Poppins} from "next/font/google";
import "./globals.css";

import {JoinUsWrapper} from "./components/home/JoinUsWrapper";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["400", "500", "600", "700"],
});

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// import {Metadata} from "next";

export const metadata: Metadata = {
  title: "Home",
  description: "Finnoto",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.className}`}>
        {/* <Navbar /> */}
        {children}
        <JoinUsWrapper />
      </body>
    </html>
  );
}
